// Generated by Bisonc++ V6.04.01 on Fri, 18 Feb 2022 00:26:39 +0100

// Include this file in the sources of the class parser.

// $insert class.h
#include "parser.hpp"

// $insert namespace-open
namespace u2d
{

parser::parser(std::istream& in, std::ostream& out, u2d::model_t& model)
    : parserBase()
    , d_scanner(in, out)
    , _model(model)
{
}

inline void parser::error()
{
    std::cerr << "Syntax error\n";
}

// $insert lex
inline int parser::lex()
{
    return d_scanner.lex();
}

inline void parser::print()
{
}

inline void parser::exceptionHandler(std::exception const& exc)
{
    throw; // re-implement to handle exceptions thrown by actions
}

// $insert namespace-close
} // namespace u2d

// Add here includes that are only required for the compilation
// of parser's sources.

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace u2d without specifying u2d::
// using namespace u2d;

// UN-comment the next using-declaration if you want to use
// int parser's sources symbols from the namespace std without
// specifying std::

// using namespace std;
