// Generated by Flexc++ V2.08.01 on Thu, 17 Feb 2022 23:49:12 +0100

// $insert class_h
#include "scanner.hpp"
#include "parser.hpp"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace u2d_parser without prefixing u2d_parser::
//using namespace u2d_parser;
